export const dogBreeds = [
  "Any",
  "Akbash",
  "Akita",
  "Alaskan Malamute",
  "American Bulldog",
  "American Bully",
  "American Eskimo Dog",
  "American Foxhound",
  "American Staffordshire Terrier",
  "Anatolian Shepherd",
  "Aussiedoodle",
  "Australian Cattle Dog",
  "Blue Heeler",
  "Australian Kelpie",
  "Australian Shepherd",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Beauceron",
  "Bedlington Terrier",
  "Belgian Shepherd / Malinois",
  "Bernedoodle",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Black and Tan Coonhound",
  "Black Labrador Retriever",
  "Black Mouth Cur",
  "Bloodhound",
  "Bluetick Coonhound",
  "Border Collie",
  "Borzoi",
  "Boston Terrier",
  "Bouvier des Flandres",
  "Boxer",
  "Boykin Spaniel",
  "Briard",
  "Brittany Spaniel",
  "Bull Terrier",
  "Bullmastiff",
  "Cairn Terrier",
  "Cane Corso",
  "Cardigan Welsh Corgi",
  "Carolina Dog",
  "Catahoula Leopard Dog",
  "Cattle Dog",
  "Cavalier King Charles Spaniel",
  "Cavapoo",
  "Chihuahua",
  "Chinese Crested Dog",
  "Chiweenie",
  "Chocolate Labrador Retriever",
  "Chow Chow",
  "Cockapoo",
  "Cocker Spaniel",
  "Collie",
  "Coonhound",
  "Corgi",
  "Dachshund",
  "Dalmatian",
  "Doberman Pinscher",
  "Dogo Argentino",
  "Dutch Shepherd",
  "English Bulldog",
  "English Coonhound",
  "English Pointer",
  "English Setter",
  "English Shepherd",
  "English Springer Spaniel",
  "Feist",
  "Flat-Coated Retriever",
  "Fox Terrier",
  "Foxhound",
  "French Bulldog",
  "German Pinscher",
  "German Shepherd Dog",
  "German Shorthaired Pointer",
  "German WireHaired Pointer",
  "Golden Retriever",
  "Goldendoodle",
  "Great Dane",
  "Great Pyrenees",
  "Greyhound",
  "Havanese",
  "Hound",
  "Husky",
  "Irish Setter",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Japanese Chin",
  "Labradoodle",
  "Labrador Retriever",
  "Maltese",
  "Manchester Terrier",
  "Mastiff",
  "Miniature Dachshund",
  "Miniature Pinscher",
  "Miniature Poodle",
  "Miniature Schnauzer",
  "Mixed Breed",
  "Mountain Cur",
  "Mountain Dog",
  "Newfoundland Dog",
  "Norfolk Terrier",
  "Norweigan Elkhound",
  "Old English Sheepdog",
  "Papillon",
  "Patterdale Terrier",
  "Fell Terrier",
  "Pekingese",
  "Peruvian Inca Orchid",
  "Pharaoh Hound",
  "Pit Bull Terrier",
  "Plott Hound",
  "Pointer",
  "Pomeranian",
  "Pomsky",
  "Poodle",
  "Pug",
  "Puggle",
  "Rat Terrier",
  "Redbone Coonhound",
  "Retriever",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Rough Collie",
  "Saint Bernard",
  "Samoyed",
  "Schipperke",
  "Schnauzer",
  "Setter",
  "Shar-Pei",
  "Shepherd",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Siberian Husky",
  "Silky Terrier",
  "Smooth Collie",
  "Spaniel",
  "Staffordshire Bull Terrier",
  "Standard Schnauzer",
  "Terrier",
  "Treeing Walker Coonhound",
  "Weimaraner",
  "Westie",
  "Whippet",
  "White German Shepherd",
  "Wirehaired Terrier",
  "Yellow Labrador Retriever",
  "Yorkshire Terrier",
];

export const dogColors = [
  "Any",
  "Apricot / Beige",
  "Bicolor",
  "Black",
  "Brindle",
  "Brown / Chocolate",
  "Golden",
  "Gray / Blue / Silver",
  "Harlequin",
  "Merle (Blue)",
  "Merle (Red)",
  "Red / Chestnut / Orange",
  "Sable",
  "Tricolor (Brown, Black, & White)",
  "White / Cream",
  "Yellow / Tan / Blond / Fawn",
];

export const catBreeds = [
  "Any",
  "Abyssinian",
  "American Bobtail",
  "American Curl",
  "American Shorthair",
  "American Wirehair",
  "Applehead Siamese",
  "Balinese",
  "Bengal",
  "Birman",
  "Bombay",
  "British Shorthair",
  "Burmese",
  "Burmilla",
  "Calico",
  "Canadian Hairless",
  "Chartreux",
  "Chausie",
  "Chinchilla",
  "Cornish Rex",
  "Cymric",
  "Devon Rex",
  "Dilute Calico",
  "Dilute Tortoiseshell",
  "Domestic Long Hair",
  "Domestic Medium Hair",
  "Domestic Short Hair",
  "Egyptian Mau",
  "Exotic Shorthair",
  "Extra-Toes-Cat / Hemingway Polydactyl",
  "Havana",
  "Himalayan",
  "Japanese Bobtail",
  "Maine Coon",
  "Manx",
  "Munchkin",
  "Norweigan Forest Cat",
  "Oriental Short Hair",
  "Oriental Tabby",
  "Persian",
  "Ragamuffin",
  "Russian Blue",
  "Siamese",
  "Silver",
  "Snowshoe",
  "Somali",
  "Sphynx / Hairless Cat",
  "Tabby",
  "Tiger",
  "Tonkinese",
  "Torbie",
  "Tortoiseshell",
  "Turkish Van",
  "Tuxedo",
];

export const catColors = [
  "Any",
  "Black",
  "Black & White / Tuxedo",
  "Blue Cream",
  "Blue Point",
  "Brown / Chocolate",
  "Buff & White",
  "Buff / Tan / Fawn",
  "Calico",
  "Chocolate Point",
  "Cream / Ivory",
  "Cream Point",
  "Dilute Calico",
  "Dilute Tortoiseshell",
  "Flame Point",
  "Gray & White",
  "Gray / Blue / Silver",
  "Lilac Point",
  "Orange & White",
  "Orange / Red",
  "Seal Point",
  "Smoke",
  "Tabby (Brown / Chocolate)",
  "Tabby (Buff / Tan / Fawn)",
  "Tabby (Gray / Blue / Silver)",
  "Tabby (Leopard / Spotted)",
  "Tabby (Orange / Red)",
  "Tabby (Tiger Striped)",
  "Torbie",
  "Tortoiseshell",
  "White",
];

export const animalSizes = [
  "Any",
  "Small",
  "Medium",
  "Large",
  "Extra Large"
]

export const animalAges = [
  "Any",
  "Baby",
  "Young",
  "Adult",
  "Senior"
]
